<a href="https://colab.research.google.com/github/Aiswarya96-creator/Aiswarya96-creator/blob/main/NumPy_activities.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
x=np.arange(10,50)
a=x.reshape(4,10)
last_col=a[:,-1]
last_col

array([19, 29, 39, 49])

In [ ]:
x=np.full((3,3),5)
y=np.arange(1,10).reshape(3,3)
sum=x+y
mul=x*y
transpose=mul.T
transpose

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

In [ ]:
x=np.random.randint(10,101,15)
y=np.where(x>50,-1,x)# in numpy to check the condition we use where
len=np.sum(x>50)
len

np.int64(9)

In [ ]:
x=np.random.random((5,4))
y=np.sum(x,axis=1)
a=np.argmax(y) # to find the index of the row
x1=np.max(x,axis=1)
x1=x1.reshape(-1,1) #or keepdims=True can also be used.
x2=np.min(x,axis=1)
x2=x2.reshape(-1,1) # keepdims=True
x_normalised=(x-x2)/(x1-x2)
x_normalised

array([[0.53869548, 0.50972799, 0.        , 1.        ],
       [1.        , 0.31349515, 0.40600398, 0.        ],
       [0.08757999, 0.55047571, 0.        , 1.        ],
       [0.79256742, 1.        , 0.94554895, 0.        ],
       [0.64420118, 0.48524234, 0.        , 1.        ]])

In [ ]:
arr=np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
a=np.unique(arr)
unique, counts = np.unique(arr, return_counts=True)
dups = unique[counts > 1]
dups

array([1, 3, 5])

In [ ]:
x=np.arange(1,37).reshape(6,6)
sub=x[1:5,1:5]
y=sub[sub%2==0]
y

array([ 8, 10, 14, 16, 20, 22, 26, 28])

In [ ]:
x=np.arange(0,12).reshape(3,4)
x=x.reshape(2,6)
flatten=x.flatten()
flatten=x.reshape(4,3)
flatten

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a=np.array([[1,2],[3,4]])
x=np.insert(a,2,[5,6],axis=0) # for inserting an array(array,position,values,axis)
x=np.insert(x,2,[7,8,9],axis=1)
x

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
x=np.concatenate((a,b,c))
x=x.reshape(3,3)
x=np.diag(x)
x

array([1, 5, 9])

In [ ]:
x=np.arange(1,21)
y=x[(x%3==0) | (x%5==0)]
y.size

9

Pandas activity

In [16]:
import numpy as np
import pandas as pd

In [18]:
data=pd.read_csv("/content/titanic_dataset.csv")
data.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
data.groupby("Sex")["Survived"].mean()*100

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

In [ ]:
data['Age'].mean()
data['Age'].median()
data['Age'].std()

14.526497332334044

In [ ]:
data['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
data[(data['Age']<18 )&
     (data['Survived']==1 )&
     (data['Sex']=='female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
156,157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16.00,0,0,35851,7.7333,NaN,Q
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,22.0250,NaN,S
208,209,1,3,"Carr, Miss. Helen ""Ellen""",female,16.00,0,0,367231,7.7500,NaN,Q
233,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,31.3875,NaN,S
237,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,26.2500,NaN,S
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
329,330,1,1,"Hippach, Miss. Jean Gertrude",female,16.00,0,1,111361,57.9792,B18,C
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,NaN,C
389,390,1,2,"Lehmann, Miss. Bertha",female,17.00,0,0,SC 1748,12.0000,NaN,C
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
446,447,1,2,"Mellinger, Miss. Madeleine Violet",female,13.00,0,1,250644,19.5000,NaN,S
448,449,1,3,"Baclini, Miss. Marie Catherine",female,5.00,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.00,0,1,3101298,12.2875,NaN,S
504,505,1,1,"Maioni, Miss. Roberta",female,16.00,0,0,110152,86.5000,B79,S
530,531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,NaN,S
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,26.2500,NaN,S
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,F4,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
691,692,1,3,"Karun, Miss. Manca",female,4.00,0,1,349256,13.4167,NaN,C
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,33.0000,NaN,S
750,751,1,2,"Wells, Miss. Joan",female,4.00,1,1,29103,23.0000,NaN,S
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.00,0,0,364516,12.4750,NaN,S
780,781,1,3,"Ayoub, Miss. Banoura",female,13.00,0,0,2687,7.2292,NaN,C
781,782,1,1,"Dick, Mrs. Albert Adrian (Vera Gillespie)",female,17.00,1,0,17474,57.0000,B20,S
830,831,1,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.00,1,0,2659,14.4542,NaN,C
853,854,1,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.00,0,0,2667,7.2250,NaN,C

In [ ]:
data['Age']=data['Age'].fillna(data['Age'].median())
data['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [20]:
data['age_group']=data['Age'].apply(lambda x: 'child' if x<18 else('adult'if x<=60 else 'senior'))
data['age_group']

0       adult
1       adult
2       adult
3       adult
4       adult
        ...
886     adult
887     adult
888    senior
889     adult
890     adult
Name: age_group, Length: 891, dtype: object

In [37]:
data.sort_values(by=['Fare'],ascending=False)[['PassengerId','Fare']].head()

     PassengerId      Fare
679          680  512.3292
258          259  512.3292
737          738  512.3292
88            89  263.0000
438          439  263.0000

In [40]:
data.groupby(['Pclass','Sex'])['Fare'].mean()

Pclass  Sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

In [46]:
data.rename(columns={'Sex':'gender','Fare':'ticket_fare'})
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'gender', 'Age', 'SibSp',
       'Parch', 'Ticket', 'ticket_fare', 'Cabin', 'Embarked', 'age_group'],
      dtype='object')

In [51]:
data.groupby(['Pclass','Survived']).size().unstack() #unstack():to reshape grouped data into a table

Survived    0    1
Pclass
1          80  136
2          97   87
3         372  119

In [58]:
data.groupby(['Pclass','gender'])['Age'].mean()

Pclass  gender
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: Age, dtype: float64